Snippets = {
    "alert.js": "alert(\"help me\")\n\n// prints:\n//\n// ReferenceError: alert is not defined\n//     at Object.<anonymous> (alert.js:1:63)\n//     at Module._compile (module.js:456:26)\n//     ...\n",
    "console_log.js": "console.log(\"foo\")\n// prints: foo\n\nconsole.log(\"foo\", \"bar\")\n// prints: foo bar\n\nconsole.log(\"a-%s-b\", 1)\n// prints: a-1-b\n\nconsole.log(\"a-%s-b %j\", 1, {x:1})\n// prints: a-1-b {\"x\":1}\n\nconsole.log(process)\n// prints: { title: 'node', ...many lines... }",
    "console_time.js": "console.time(\"foo\")\ndoStuff()\nconsole.timeEnd(\"foo\")\n\nfunction doStuff() {\n\t// takes a long time\n}\n\n// prints: foo: 1121ms",
    "console_trace.js": "function a() { b() }\nfunction b() { c() }\nfunction c() { console.trace(\"foo\") }\n\na()\n\n// Trace: foo\n//     at c (<program>:3:24)\n//     at b (<program>:2:16)\n//     at a (<program>:1:78)\n//     at ...",
    "long-stack-traces-after.js": "require(\"long-stack-traces\")\na()\n\nfunction a() { setTimeout(b, 100) }\nfunction b() { setTimeout(c, 100) }\nfunction c() { throw new Error(\"foo\") }\n\n// Uncaught Error: foo\n//     at [object Object].c (/path/to/long-stack-traces.js:7:22)\n//     at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)\n// ----------------------------------------\n//     at Object.setTimeout\n//     at [object Object].b (/path/to/long-stack-traces.js:5:16)\n//     at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)\n// ----------------------------------------\n//     at Object.setTimeout\n//     at a (/path/to/long-stack-traces.js:3:16)\n//     ...",
    "long-stack-traces-before.js": "\na()\n\nfunction a() { setTimeout(b, 100) }\nfunction b() { setTimeout(c, 100) }\nfunction c() { throw new Error(\"foo\") }\n\n// Error: foo\n//     at c [as _onTimeout] (/Users/pmuellr/Projects/slides/2014/04-debugging-node/snippets/long-stack-traces-before.js:6:22)\n//     at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)",
    "q-longStack-after.js": "Q = require(\"q\")\nQ.longStackSupport = true\n\nfunction a() { Q.delay(100).done(b) }\nfunction b() { throw new Error(\"foo\") }\n\na()\n\n// Error: foo\n//     at b (/Users/pmuellr/Projects/slides/2014/04-debugging-node/snippets/q-longStack-after.js:5:22)\n// From previous event:\n//     at a (/Users/pmuellr/Projects/slides/2014/04-debugging-node/snippets/q-longStack-after.js:4:29)\n//     at Object.<anonymous> (/Users/pmuellr/Projects/slides/2014/04-debugging-node/snippets/q-longStack-after.js:7:1)",
    "q-longStack-before.js": "Q = require(\"q\")\n\n\nfunction a() { Q.delay(100).done(b) }\nfunction b() { throw new Error(\"foo\") }\n\na()\n\n// Error: foo\n//     at b (/Users/pmuellr/Projects/slides/2014/04-debugging-node/snippets/q-longStack-before.js:5:22)\n//     at _fulfilled (/Users/pmuellr/Projects/slides/2014/04-debugging-node/snippets/node_modules/q/q.js:787:54)\n//     at self.promiseDispatch.done (/Users/pmuellr/Projects/slides/2014/04-debugging-node/snippets/node_modules/q/q.js:816:30)\n//     at Promise.promise.promiseDispatch (/Users/pmuellr/Projects/slides/2014/04-debugging-node/snippets/node_modules/q/q.js:749:13)\n//     at /Users/pmuellr/Projects/slide",
    "repl.js": "repl = require(\"repl\")",
    "v8_normalStackTrace.js": "function a() { b() }\nfunction b() { c() }\nfunction c() { throw new Error(\"foo blatz\") }\n\ntry { a() } catch(err) { console.log(err.stack) }\n// prints:\n// Error: foo blatz\n//    v8_prepareStackTrace.js  14 - c()\n//    v8_prepareStackTrace.js  13 - b()\n//    v8_prepareStackTrace.js  12 - a()\n",
    "v8_prepareStackTrace-after.js": "Error.prepareStackTrace = function(err, stackTrace) { ... }\ntry { a() } catch(err) { console.log(err.stack) }\nfunction a() { b() }\nfunction b() { c() }\nfunction c() { throw new Error(\"foo blatz\") }\n\n// Error: foo blatz\n//    v8_prepareStackTrace-after.js  13 - c()\n//    v8_prepareStackTrace-after.js  12 - b()\n//    v8_prepareStackTrace-after.js  11 - a()",
    "v8_prepareStackTrace-before.js": "\ntry { a() } catch(err) { console.log(err.stack) }\nfunction a() { b() }\nfunction b() { c() }\nfunction c() { throw new Error(\"foo blatz\") }\n\n// Error: foo blatz\n//     at c (/Users/pmuellr/Projects/slides/2014/04-debugging-node/snippets/v8_prepareStackTrace-before.js:5:22)\n//     at b (/Users/pmuellr/Projects/slides/2014/04-debugging-node/snippets/v8_prepareStackTrace-before.js:4:16)\n//     at a (/Users/pmuellr/Projects/slides/2014/04-debugging-node/snippets/v8_prepareStackTrace-before.js:3:16)\n//     at Object.<anonymous> (/Users/pmuellr/Projects/slides/2014/04-debugging-node/snippets/v8_prepareStackTrace-before.js:2:7)\n//     at Module._compile (module.js:456:26)\n//     at Object.Module._extensions..js (module.js:474:10)\n//     ...",
    "winston.js": "var winston = require(\"winston\")\n\nwinston.remove(winston.transports.Console)\nwinston.add(winston.transports.Console, { level:\"warn\" })\nwinston.add(winston.transports.File, {\n\tfilename: \"somefile.log\" }\n)\n\nwinston.info(\"info message\")\nwinston.warn(\"warning message\")\nwinston.error(\"error message\")\n\n// prints:\n// warn: warning message\n// error: error message"
}