all: copyFiles runSamples

SRC=~/Projects/slides/2016/01-intro-to-profiling/intro-to-profiling
DST=~/Dropbox\ \(NodeSource\)/2016-01-intro-to-profiling

copyFiles:
	@date
	cp intro-to-profiling.key ~/Dropbox\ \(NodeSource\)/2016-01-intro-to-profiling.key
	cp intro-to-profiling.pdf ~/Dropbox\ \(NodeSource\)/2016-01-intro-to-profiling.pdf

runSamples:
	cd samples; nsolid run
